POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de Docker"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/5647135c-4aac-4d07-ba47-8b94764105b8
